apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: display-results
spec:
  workspaces:
    - name: output
      description: Directory where application source is located.
      optional: true
    - name: cache
      description: Directory where cache is stored (when no cache image is provided).
      optional: true
  params:
    - name: DIGEST
    - name: URL
    - name: COMMIT
  steps:
    - name: print
      image: docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6
      script: |
        #!/usr/bin/env bash
        set -e
        echo "Digest of created app image: $(params.DIGEST)"
        echo "URL of created app image: $(params.URL)"
        echo "COMMIT of repo: $(params.COMMIT)"
        echo "------list workspaces.cache------"
        ls -la $(workspaces.cache.path)/committed

