apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  workspaces:
    - name: output
      workspace: source-workspace
  params:
#    - name: DIGEST
#    - name: URL
#    - name: COMMIT
  steps:
    - name: unit-test
      image: golang:alpine
      script: |
        echo "Begining to go test"
        cd $(workspaces.output.path)
        ls -la
        go test .
