apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jx-demo-pipeline-run
spec:
  pipelineRef:
    name: jx-demo-pipeline
  workspaces:
    - name: source-workspace
      subPath: source
      persistentVolumeClaim:
        claimName: buildpacks-source-pvc
    - name: cache-workspace
      subPath: cache
      persistentVolumeClaim:
        claimName: buildpacks-source-pvc
  params:
    - name: argocd-url
      value: "argocd-server.argocd" #argocd-server service address
    - name: argocd-secret
      value: "argocd-oauth" #must be create secret for argocd username and password
    - name: repo-url
      value: "https://github.com/gitcpu-io/jx-demo" #code repo
    - name: repo-revision
      value: ""
    - name: repo-image
      value: "rubinus/jx-demo"  #image url for docker registry
    - name: app-name
      value: "jx-demo"  #argocd application name must be create before on the argocd
    - name: app-revision
      value: ""

  serviceAccountName: buildpacks-service-account
