apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jx-demo-pre-pipeline
spec:
  workspaces:
    - name: source-workspace  # Directory where application source is located.
  params:
    - name: repo-url
    - name: repo-revision
      type: string
      default: "master"
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
      params:
        - name: deleteExisting
          value: "true"
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
    - name: test
      taskRef:
        name: test
      workspaces:
        - name: output
          workspace: source-workspace


