replicaCount: 1
image:
  repository: rubinus/jx-demo
  pullPolicy: IfNotPresent
  tag: 9c32b6b392b8c2d020c77352fe7748c80ff9c2b8
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  targetPort: 8081
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
  - host: jx-demo.gitpops.net
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
